### ISSUE TITLE
Error in checkbox, radiogroup & dropdown

### ISSUE THREAD

**Issue by dipen211** [surveyjs/survey-creator#2591]
### Are you requesting a feature, reporting a bug or ask a question?

when i click for this 3 question then i get error in console.

### What is the current behavior?
Console Error

Uncaught TypeError: this.question.getAriaItemLabel is not a function
    at SurveyQuestionCheckboxItem.renderCheckbox (reactquestion_checkbox.tsx:173:1)
    at SurveyQuestionCheckboxItem.renderElement (reactquestion_checkbox.tsx:151:1)
    at SurveyQuestionCheckboxItem.SurveyElementBase.render (reactquestion_element.tsx:42:1)
    at finishClassComponent (react-dom.development.js:17485:1)
    at updateClassComponent (react-dom.development.js:17435:1)
    at beginWork (react-dom.development.js:19073:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at HTMLUnknownElement.sentryWrapped (helpers.ts:88:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
    at workLoopSync (react-dom.development.js:22707:1)
    at renderRootSync (react-dom.development.js:22670:1)
    at performSyncWorkOnRoot (react-dom.development.js:22293:1)
    at react-dom.development.js:11327:1
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322:1)
    at flushSyncCallbackQueue (react-dom.development.js:11309:1)
    at discreteUpdates$1 (react-dom.development.js:22420:1)
    at discreteUpdates (react-dom.development.js:3756:1)
    at dispatchDiscreteEvent (react-dom.development.js:5889:1)
    at HTMLDivElement.sentryWrapped (helpers.ts:88:1)

### What is the expected behavior?

Need to display checkbox button question

* editor version: "survey-creator-react": "^1.9.6-beta.1",

**Comment by tsv2013** [comment]
How can we reproduce it on our side?
