### ISSUE TITLE
Change survey complete text

### ISSUE THREAD

**Issue by dipen211** [surveyjs/survey-creator#2626]
I try to change completed html text using below code in surveycreator

        var currentText = JSON.parse(surveyCreator.current.text);
        currentText.completedHtml = "<h3>xxxxx........................xxxxx</h3>";
        surveyCreator.current.json = JSON.stringify(currentText);
        
in surveycreatorv2 this code not work it show below error...

Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'canShowErrors')
    at new TabJsonEditorTextareaComponent (bundle.js:441400:39)
    at constructClassInstance (bundle.js:374619:13)
    at updateClassComponent (bundle.js:379244:9)
    at beginWork (bundle.js:380839:20)
    at HTMLUnknownElement.callCallback (bundle.js:365804:18)
    at HTMLUnknownElement.sentryWrapped (bundle.js:80121:17)
    at Object.invokeGuardedCallbackDev (bundle.js:365853:20)
    at invokeGuardedCallback (bundle.js:365913:35)
    at beginWork$1 (bundle.js:385655:11)
    at performUnitOfWork (bundle.js:384491:16)
    at workLoopSync (bundle.js:384428:9)
    at renderRootSync (bundle.js:384394:11)
    at performSyncWorkOnRoot (bundle.js:384011:22)
    at bundle.js:373264:30
    at unstable_runWithPriority (bundle.js:391083:16)
    at runWithPriority$1 (bundle.js:373210:14)
    at flushSyncCallbackQueueImpl (bundle.js:373259:13)
    at flushSyncCallbackQueue (bundle.js:373247:7)
    at scheduleUpdateOnFiber (bundle.js:383611:13)
    at Object.enqueueSetState (bundle.js:374387:9)
    at SurveyCreatorComponent.Component.setState (bundle.js:269609:20)
    at SurveyCreator.stateElement.setPropertyValueCoreHandler (bundle.js:452242:23)
    at SurveyCreator.Base.setPropertyValueCore (bundle.js:298146:22)
    at SurveyCreator.Base.setPropertyValueDirectly (bundle.js:298209:18)
    at SurveyCreator.Base.setPropertyValue (bundle.js:298191:20)
    at SurveyCreator.set (bundle.js:313971:24)
    at SurveyCreator.CreatorBase.changeText (bundle.js:406346:37)
    at SurveyCreator.set (bundle.js:406363:28)
    at bundle.js:15825:36
    at commitHookEffectListMount (bundle.js:249583:30)
    at commitPassiveHookEffects (bundle.js:249620:15)
    at HTMLUnknownElement.callCallback (bundle.js:230165:18)
    at HTMLUnknownElement.sentryWrapped (bundle.js:80121:17)
    at Object.invokeGuardedCallbackDev (bundle.js:230214:20)
    at invokeGuardedCallback (bundle.js:230267:35)
    at flushPassiveEffectsImpl (bundle.js:252684:13)
    at unstable_runWithPriority (bundle.js:277003:16)
    at runWithPriority$1 (bundle.js:241052:14)
    at flushPassiveEffects (bundle.js:252652:16)
    at performSyncWorkOnRoot (bundle.js:251567:7)
    at bundle.js:241106:28
    at unstable_runWithPriority (bundle.js:277003:16)
    at runWithPriority$1 (bundle.js:241052:14)
    at flushSyncCallbackQueueImpl (bundle.js:241101:11)
    at flushSyncCallbackQueue (bundle.js:241089:7)
    at scheduleUpdateOnFiber (bundle.js:251029:13)
    at dispatchAction (bundle.js:245609:9)
    at fetchClients (bundle.js:19405:7)

**Comment by dipen211** [comment]
Solved

**Comment by chegor** [comment]
@dipen211 Could you please provide a way how you override default completedHtml?

**Comment by dipen211** [comment]
@chegor 
const surveyCreator = new SurveyJSCreator.SurveyCreator();

var currentText = JSON.parse(surveyCreator.text);
currentText.completedHtml = 'YOUR TEXT HERE';
surveyCreator.text = JSON.stringify(currentText);
