### ISSUE TITLE
The Cannot read properties of null (reading 'dragDropStart') error is thrown on an attempt to drag and drop a question

### ISSUE THREAD

**Issue by JaneGaid** [surveyjs/survey-creator#3432]
```
Uncaught TypeError: Cannot read properties of null (reading 'dragDropStart')
    at ./src/dragdrop/survey-elements.ts.DragDropSurveyElements.insertGhostElementIntoSurvey (survey-elements.ts:360:24)
    at ./src/dragdrop/survey-elements.ts.DragDropSurveyElements.afterDragOver (survey-elements.ts:302:10)
    at DragDropCore._this.dragOver (core.ts:233:10)
```

**Comment by dmitrykurmanov** [comment]
steps:
1. set json
```json
{
 "logoPosition": "right",
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "paneldynamic",
     "name": "question2",
     "title": "paneldynamic",
     "templateElements": [
      {
       "type": "panel",
       "name": "panel1",
       "elements": [
        {
         "type": "rating",
         "name": "question3"
        },
        {
         "type": "rating",
         "name": "question4",
         "startWithNewLine": false
        }
       ],
       "title": "panel"
      }
     ]
    },
    {
     "type": "rating",
     "name": "question1"
    }
   ]
  }
 ]
}
```

2. try to drag from the toolbox to "paneldynamic" below "panel"

**Comment by dmitrykurmanov** [comment]
fixed via https://github.com/surveyjs/survey-library/pull/4849/commits/286a1f1ed08a10bd93f396b7904e38e8d956faf8
