### ISSUE TITLE
Survey Creator with Custom Widgets - The Cannot read properties of undefined (reading 'getType') exception is thrown on an attempt to add a new question

### ISSUE THREAD

**Issue by JaneGaid** [surveyjs/survey-creator#3454]
To reproduce the issue, run the [Survey Creator | Custom Widgets | React demo](https://surveyjs.io/survey-creator/examples/customwidgets/reactjs) in CodeSandbox, and click Add Question. The following exception is thrown:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'getType')
    at ./src/property-grid/index.ts.PropertyJSONGenerator.createJSON (index.ts:533:28)
    at ./src/property-grid/index.ts.PropertyJSONGenerator.toJSON (index.ts:457:17)
    at ./src/property-grid/index.ts.PropertyJSONGenerator.setupObjPanel (index.ts:470:25)
    at ./src/property-grid/restfull.ts.PropertyGridEditorQuestionRestfull.onCreated (restfull.ts:42:67)
    at Object.onCreated (index.ts:222:11)
    at ./src/property-grid/index.ts.PropertyJSONGenerator.onQuestionsCreated (index.ts:497:36)
    at ./src/property-grid/index.ts.PropertyJSONGenerator.setupObjPanel (index.ts:471:10)
    at ./src/property-grid/index.ts.PropertyGridModel.setObj (index.ts:757:55)
    at PropertyGridModel.set (index.ts:700:10)
    at ./src/creator-base.ts.CreatorBase.selectionChanged (creator-base.ts:2511:36)
    at ./src/creator-base.ts.CreatorBase.selectElement (creator-base.ts:2362:12)
    at ./src/creator-base.ts.CreatorBase.clickToolboxItem (creator-base.ts:2538:12)
    at ./src/creator-base.ts.CreatorBase.addNewQuestionInPage (creator-base.ts:3050:10)
    at descriptor.value [as addNewQuestionInPage] (index.ts:53:40)
    at ./src/components/page.ts.PageAdorner.addNewQuestion (page.ts:108:18)
    at onClick (Page.tsx:102:20)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:25)
    at executeDispatch (react-dom.development.js:9041:3)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:7)
    at processDispatchQueue (react-dom.development.js:9086:5)
    at dispatchEventsForPlugins (react-dom.development.js:9097:3)
    at eval (react-dom.development.js:9288:12)
    at batchedUpdates$1 (react-dom.development.js:26140:12)
    at batchedUpdates (react-dom.development.js:3991:12)
    at dispatchEventForPluginEventSystem (react-dom.development.js:9287:3)
    at dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay (react-dom.development.js:6465:5)
    at dispatchEvent (react-dom.development.js:6457:5)
    at dispatchDiscreteEvent (react-dom.development.js:6430:5)
```
[CodeSandbox Link](https://codesandbox.io/s/broken-monad-i0rh8x).
![image](https://user-images.githubusercontent.com/22372972/191532638-d9c60e25-4eb8-4eaa-bbd5-9c7ab1d12a88.png)

This issue was reported at:
* [T10682 - Custom widget - TypeError: Cannot read property 'getType' of undefined](https://surveyjs.answerdesk.io/internal/ticket/details/T10682)
* [T10688 - Add CKEditor during survey creation](https://surveyjs.answerdesk.io/internal/ticket/details/T10688)

**Comment by tsv2013** [comment]
Right now works ok for me. Probably I missed something...

**Comment by andrewtelnov** [comment]
@tsv2013 I was able to reproduce the issue. Autocomplete widget cause the problem.

Thank you,
Andrew

**Comment by Jrejoire** [comment]
Hello @tsv2013,

Here is a simple example where I had the issue. It's with my stack React/Typescript:
https://github.com/Jrejoire/survey_example

Thanks for your help.

**Comment by andrewtelnov** [comment]
@Jrejoire @JaneGaid I have fixed the issue in Custom widget repository.
The issue was with Autocomplete widget.

Thank you,
Andrew
