### ISSUE TITLE
The 'unable to process binding "class: function(){return className }"' exception is thrown in the onGetPropertyReadOnly event for radio/checkbox question types

### ISSUE THREAD

**Issue by rendaforstmane** [surveyjs/survey-creator#3658]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
Whenever I add the `onGetPropertyReadOnly` event and add the `radio/checkbox` question types, after the `None/Other` options selection I get some error in the console. When switching to the "Preview" tab and back, those texts from other/none disappear.

<img width="758" alt="Screenshot 2022-11-10 at 17 06 31" src="https://user-images.githubusercontent.com/84146240/201131408-3c82831c-5149-457e-aa34-ad9210292d95.png">

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
You can test it on this page. The newest surveyJS version added
https://plnkr.co/edit/HRJl0bJaBiVLRpvd?preview
Test code

```
your_code_here

creator.onGetPropertyReadOnly.add((sender, options) => {))

### Specify your

* browser: safari/chrome
* editor version: 1.9.57

**Comment by JaneSjs** [comment]
Hello @rendaforstmane,
Thank you for reporting this issue. I reproduced the following error:
```
knockout-latest.js:16 Uncaught TypeError: Unable to process binding "class: function(){return className }"
Message: Cannot read properties of null (reading 'name')
    at t.onIsPropertyReadOnlyCallback (survey-creator-core.min.js:13:433317)
    at t.isCanModifyProperty (survey-creator-core.min.js:13:432900)
    at t.get (survey-creator-core.min.js:13:415540)
    at t.className (survey-creator-core.min.js:13:415763)
    at e.get (survey-creator-knockout.min.js:7:58023)
    at class (eval at parseBindingsString (knockout-latest.js:74:172), <anonymous>:3:58)
    at update (knockout-latest.js:99:144)
    at a.$.l (knockout-latest.js:79:379)
    at Function.yd (knockout-latest.js:55:359)
    at Function.zd (knockout-latest.js:55:45)
```
We will research it and post updates.

Thank you
