### ISSUE TITLE
Cannot read properties of undefined (reading 'indexOf') is thrown when inserting a custom toolbox item using an index

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#3799]
Original Issue: [T11809 - Register a custom component based on a Text question](https://surveyjs.answerdesk.io/internal/ticket/details/T11809)
***
Run the following code to insert a custom toolbox item at 0 position.
```
creator.toolbox.addItem({
        name: "email",
        title: "Email",
        json: {
            type: "text",
            inputType: "email"
        }}, 0);
```
[Example](https://plnkr.co/edit/ylanLbT5pNgg3GLD).
Now, click the custom question's toolbox icon to add the custom question to a design surface. The creator fails with the following exception.
```
Uncaught TypeError: Cannot read properties of undefined (reading 'indexOf')
    at t.onPointerDown (survey-creator-core.min.js:13:471509)
    at onPointerDown (survey-creator-react.min.js:7:47441)
    at Object.lj (react-dom.production.min.js:223:217)
    at kj (react-dom.production.min.js:34:117)
    at nj (react-dom.production.min.js:34:171)
    at gh (react-dom.production.min.js:62:93)
    at Xg (react-dom.production.min.js:63:1)
    at react-dom.production.min.js:72:332
    at Tf (react-dom.production.min.js:189:448)
    at wg (react-dom.production.min.js:32:481)
t.onPointerDown @ survey-creator-core.min.js:13
onPointerDown @ survey-creator-react.min.js:7
lj @ react-dom.production.min.js:223
kj @ react-dom.production.min.js:34
nj @ react-dom.production.min.js:34
gh @ react-dom.production.min.js:62
Xg @ react-dom.production.min.js:63
(anonymous) @ react-dom.production.min.js:72
Tf @ react-dom.production.min.js:189
wg @ react-dom.production.min.js:32
Ce @ react-dom.production.min.js:65
Be @ react-dom.production.min.js:47
Aj @ react-dom.production.min.js:46
```
As a temporary solution, do not

**Comment by andrewtelnov** [comment]
Please use the following code: 
```js
creator.toolbox.addItem({
        id: "email",
        title: "Email",
        json: {
            type: "text",
            inputType: "email"
        }}, 0);
```

Thank you,
Andrew
