### ISSUE TITLE
Multiple-Choice Matrix in Vertical orientation - The Cannot read properties of null (reading 'whenPanelFocusIn') exception is thrown when selecting a Radiogroup option for a Vertical Matrix

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#3846]
To reproduce the issue:
* Drop a Multiple-Choice Matrix to a survey;
* Navigate to Layout -> Enable the Vertical column orientation
* Select the first matrix column;
* Change its `Cell type` to `Radiogroup`.
* The following exception is thrown:
```
survey.core.min.js:6 Uncaught TypeError: Cannot read properties of null (reading 'whenPanelFocusIn')
    at n.focusIn (survey.core.min.js:6:729377)
    at HTMLDivElement.<anonymous> (knockout.js:445:350)
    at t.updateOnHiding (survey.core.min.js:24:94684)
    at t.updateOnHiding (survey.core.min.js:24:102228)
    at Object.n [as func] (survey.core.min.js:24:92019)
    at e.propertyValueChanged (survey.core.min.js:6:134224)
    at e.setPropertyValue (survey.core.min.js:6:133058)
    at t.set (survey.core.min.js:6:190245)
    at t.onBlur (survey.core.min.js:6:645302)
    at Object.blur (survey-knockout-ui.min.js:6:174091)
```
See this video:
https://user-images.githubusercontent.com/22372972/219423352-4f0cb171-3484-45eb-8bd0-aa396308ed0e.mp4

***
Issue 2: Proceed with editing the Radiogroup column:
* Select Column1;
* Open the Choice property grid category;
* Add two custom choices.
* The following exception is thrown:
```
survey.core.min.js:6 Uncaught TypeError: Cannot read properties of null (reading 'locText')
    at e.get (survey.core.min.js:6:336095)
    at attr (eval at parseBindingsString (knockout.js:305:238), <anonymous>:3:204)
    at update (knockout.js:425:43)
    at a.$.l (knockout.js:336:468)
    at Function.yd (knockout.js:205:95)
    at Function.zd (knockout.js:204:61)
    at Function.ha (knockout.js:200:404)
    at Function.Hc (knockout.js:200:203)
    at Function.notifySubscribers (knockout.js:140:516)
    at Function.xa (knockout.js:154:154)
```
* Navigate to Preview, and back to the designer: rows disappear.
See this video:
https://user-images.githubusercontent.com/22372972/219424243-a9e33147-4224-44b8-b4fd-eea43547acdd.mp4

**Comment by andrewtelnov** [comment]
Fixed in the library. We need to add a functional test on this functionality.

Thank you,
Andrew
