### ISSUE TITLE
'Apply' button in Edit Totals popup causes console error 'Cannot read properties of null'

### ISSUE THREAD

**Issue by LynxJ** [surveyjs/survey-creator#3916]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

Click on the 'Edit' icon in Total field for column opens popup that contains only the name of the column, Cancel and Apply buttons. Click on the 'Apply' button causes console error `TypeError: Cannot read properties of null (reading 'getColumnByName')`.

![image](https://user-images.githubusercontent.com/51529927/226948003-1d259f49-9d04-4a55-88cd-2ac0c0fb883a.png)

### What is the expected behavior?

1. Edit popup should contain some information to be edited.
2. 'Apply' button should close popup and apply changes that were done.

### How would you reproduce the current behavior (if this is a bug)?
1. Add Multiple-Choice or Dynamic Matrix to the survey.
2. Click on column title in the middle panel.
3. In the right panel add Totals to the column (e.g Total type = Sum, Total value display style=decimal, Currency=USD).
4. In the middle panel hover mouse over Total value and click appeared Edit icon.
5. Open DevTools.
6. Click 'Apply' button.

It is reproducible even on the survey-creator/examples/free-nps-survey-template page.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs.io/survey-creator/examples/free-nps-survey-template/angular

### Specify your

* browser: 
Google Chrome 
Version 111.0.5563.111 (64-bit)
* editor version:

**Comment by JaneSjs** [comment]
Hello @LynxJ,
Thank you for reporting this issue. We will research it and let you know our results.
***
- [ ] Why the popup is displayed for the summary label? (A popup should contain summary settings)
- [ ] The exception occurs on clicking 'Apply'
[Example](https://codesandbox.io/s/headless-framework-5oypov?file=/src/survey_json.js)

![image](https://user-images.githubusercontent.com/22372972/227336200-f7329d6f-e47b-4e99-81dc-60a432031c01.png)
```
react-dom.development.js:4312 Uncaught TypeError: Cannot read properties of null (reading 'getColumnByName')
    at ./src/components/matrix-cell.ts.MatrixCellWrapperEditSurvey.apply (survey-creator-core.js:1084:29)
    at PopupModel.eval (survey-creator-core.js:1126:24)
    at ./src/popup-modal-view-model.ts.PopupModalViewModel.apply (survey.core.js:22468:49)
    at Action.action (survey.core.js:22457:41)
    at onClick (survey-react-ui.js:1622:271)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:25)
    at executeDispatch (react-dom.development.js:9041:3)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:7)
    at processDispatchQueue (react-dom.development.js:9086:5)
    at dispatchEventsForPlugins (react-dom.development.js:9097:3)
    at eval (react-dom.development.js:9288:12)
    at batchedUpdates$1 (react-dom.development.js:26140:12)
    at batchedUpdates (react-dom.development.js:3991:12)
    at dispatchEventForPluginEventSystem (react-dom.development.js:9287:3)
    at dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay (react-dom.development.js:6465:5)
    at dispatchEvent (react-dom.development.js:6457:5)
    at dispatchDiscreteEvent (react-dom.development.js:6430:5)
```
