### ISSUE TITLE
The Maximum call stack size exceeded exception is raised on an attempt to add a question which uses jQuery Inputmask as a Property Grid editor

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#4140]
I registered a jQuery Inputmask widget and want to use it as a custom property grid editor:
```js
function SurveyCreatorRenderComponent() {
  SurveyCore.Serializer.addProperty("question", {
  name: "timeDelay",
  category: "general",
  type: "timeDelayProp",
  default: 0
});
PropertyGridEditorCollection.register({
  fit: function (prop) {
    return prop.name === "timeDelay";
  },
  getJSON: function (obj, prop, options) {
    return {
      type: "text",
      inputMask: "integer"
    };
  }
});
```
[Example](https://codesandbox.io/s/crazy-shape-nbee5s?file=/src/SurveyCreatorComponent.jsx)

The following exception is thrown when I add a new question: **Maximum call stack size exceeded**
```
The above error occurred in the <SurveyCustomWidget> component:
    at SurveyCustomWidget (https://nbee5s.csb.app/node_modules/survey-react-ui/survey-react-ui.js:3954:28)

    at div

    at div

    at SurveyQuestion (https://nbee5s.csb.app/node_modules/survey-react-ui/survey-react-ui.js:6142:28)

    at div

    at div

    at SurveyRow (https://nbee5s.csb.app/node_modules/survey-react-ui/survey-react-ui.js:9890:28)

    at div

    at div

    at SurveyPanel (https://nbee5s.csb.app/node_modules/survey-react-ui/survey-react-ui.js:5170:28)

    at div

    at div

    at SurveyRow (https://nbee5s.csb.app/node_modules/survey-react-ui/survey-react-ui.js:9890:28)

    at div

    at SurveyPage (https://nbee5s.csb.app/node_modules/survey-react-ui/survey-react-ui.js:4942:23)

    at div

    at div

    at div

    at form

    at div

    at Survey (https://nbee5s.csb.app/node_modules/survey-react-ui/survey-react-ui.js:5476:28)

    at PropertyGridComponent (https://nbee5s.csb.app/node_modules/survey-creator-react/survey-creator-react.js:812:42)

    at SidebarTab (https://nbee5s.csb.app/node_modules/survey-creator-react/survey-creator-react.js:1219:42)

    at div

    at div

    at div

    at div

    at SidebarComponent (https://nbee5s.csb.app/node_modules/survey-creator-react/survey-creator-react.js:1164:28)

    at div

    at div

    at div

    at div

    at SurveyCreatorComponent (https://nbee5s.csb.app/node_modules/survey-creator-react/survey-creator-react.js:1482:28)

    at SurveyCreatorRenderComponent
Consider adding an error boundary to your tree to customize error handling behavior.

Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries. 

    in Unknown
```

**Comment by JaneSjs** [comment]
The issue occurs in an Angular CodeSandbox demo only.
