### ISSUE TITLE
Unhandled error after remove page id

### ISSUE THREAD

**Issue by proxime** [surveyjs/survey-creator#4142]
### Are you requesting a feature, reporting a bug or ask a question?
bug

### What is the current behavior?
When delete page id in Pages tab:

![image](https://github.com/surveyjs/survey-creator/assets/53379886/49ecd7c6-635a-4645-9b95-0d60daec81b0)

App frooze for 2s and in console we got error:
`Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at t.isNameUniqueInArray (2.6a5ab91d.chunk.js:2:10853337)
    at t.isNameUnique (2.6a5ab91d.chunk.js:2:10853090)
    at t.generateUniqueName (2.6a5ab91d.chunk.js:2:10852819)
    at t.getErrorOnPropertyChanging (2.6a5ab91d.chunk.js:2:10852581)
    at t.onGetErrorTextOnValidationCallback (2.6a5ab91d.chunk.js:2:10855681)
    at e.validateQuestionValue (2.6a5ab91d.chunk.js:2:11069720)
    at e.onMatrixCellValidate (2.6a5ab91d.chunk.js:2:11072293)
    at Array.<anonymous> (2.6a5ab91d.chunk.js:2:11067112)
    at e.fire (2.6a5ab91d.chunk.js:2:6599318)
    at t.matrixCellValidate (2.6a5ab91d.chunk.js:2:7579871)
    at t.validateCell (2.6a5ab91d.chunk.js:2:7264810)
    at i.validateValueCallback (2.6a5ab91d.chunk.js:2:7224854)
    at t.fireSurveyValidation (2.6a5ab91d.chunk.js:2:7049464)
    at t.collectErrors (2.6a5ab91d.chunk.js:2:7049291)
    at t.checkForErrors (2.6a5ab91d.chunk.js:2:7048961)
    at t.hasErrors (2.6a5ab91d.chunk.js:2:7047948)
    at e.hasQuestonError (2.6a5ab91d.chunk.js:2:7232875)
    at e.setValueCore (2.6a5ab91d.chunk.js:2:7232383)
    at e.setValue (2.6a5ab91d.chunk.js:2:7231538)
    at t.setValueCore (2.6a5ab91d.chunk.js:2:7051720)
    at t.setNewValueInData (2.6a5ab91d.chunk.js:2:7051500)
    at t.setNewValue (2.6a5ab91d.chunk.js:2:7050825)
    at t.setNewValue (2.6a5ab91d.chunk.js:2:7455465)
    at t.setNewValue (2.6a5ab91d.chunk.js:2:7448084)
    at t.set (2.6a5ab91d.chunk.js:2:7038523)
    at t.updateValueOnEvent (2.6a5ab91d.chunk.js:2:7448703)
    at n.onBlur (2.6a5ab91d.chunk.js:2:7439212)
    at Object.Ye (2.6a5ab91d.chunk.js:2:10100711)
    at We (2.6a5ab91d.chunk.js:2:10100865)
    at 2.6a5ab91d.chunk.js:2:10119090
    at Sr (2.6a5ab91d.chunk.js:2:10119184)
    at Dr (2.6a5ab91d.chunk.js:2:10119599)
    at 2.6a5ab91d.chunk.js:2:10125240
    at Le (2.6a5ab91d.chunk.js:2:10200920)
    at 2.6a5ab91d.chunk.js:2:10121060
    at jr (2.6a5ab91d.chunk.js:2:10121090)
    at en (2.6a5ab91d.chunk.js:2:10109143)
    at $t (2.6a5ab91d.chunk.js:2:10108369)
    at t.unstable_runWithPriority (2.6a5ab91d.chunk.js:2:10206903)
    at Ji (2.6a5ab91d.chunk.js:2:10129440)
    at Re (2.6a5ab91d.chunk.js:2:10200659)
    at qt (2.6a5ab91d.chunk.js:2:10108161)`

And also so much renders:
![image](https://github.com/surveyjs/survey-creator/assets/53379886/9760a259-5b7c-4bf9-838d-93f16da82120)

### What is the expected behavior?
app shouldn't frooze

### How would you reproduce the current behavior (if this is a bug)?
remove page id

### Specify your

* browser: Chrome Version:113.0.0

**Comment by andrewtelnov** [comment]
@proxime I have just tried and I could not reproduce the issue. What version and platform do you use?

Thank you,
Andrew

**Comment by proxime** [comment]
Windows 10,
survey version 1.9.86

**Comment by JaneSjs** [comment]
Hello @proxime,
Thank you for the clarification. I reproduce the issue.
1. Open https://surveyjs.io/survey-creator/examples/free-nps-survey-template/reactjs.
2. Navigate to a Pages survey property grid category
3. Clear the page1 text

The following exception occurs.
```
react-dom.production.min.js:63 Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at t.isNameUniqueInArray (survey-creator-core.min.js:13:536052)
    at t.isNameUnique (survey-creator-core.min.js:13:535803)
    at t.generateUniqueName (survey-creator-core.min.js:13:535544)
    at t.getErrorOnPropertyChanging (survey-creator-core.min.js:13:535318)
    at t.onGetErrorTextOnValidationCallback (survey-creator-core.min.js:13:538396)
    at e.validateQuestionValue (survey-creator-core.min.js:13:295385)
    at e.onMatrixCellValidate (survey-creator-core.min.js:13:298165)
    at Array.<anonymous> (survey-creator-core.min.js:13:292371)
    at e.fire (survey.core.min.js:6:155618)
    at t.matrixCellValidate (survey.core.min.js:6:359832)
```
