### ISSUE TITLE
Programmatically updating a custom 'itemvalues' property doesn't work

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#4592]
User Issue: T14528 - Customize 'itemvalues' property or add custom component as property
https://surveyjs.answerdesk.io/internal/ticket/details/T14528
***
Usage Scenario: create a custom property of an `itemvalues` type. Within the other property's `onSetValue` function, update the `itemvalues` property and assign a new array of values.
[View Demo](https://codesandbox.io/s/reverent-violet-jkfyjz?file=/src/SurveyCreatorComponent.jsx:387-995)
```
Serializer.addProperty("survey", {
  name: "customChoices",
  type: "itemvalues",
  default: [
    { value: 0, text: "Item 0" },
    { value: 1, text: "Item 1" },
    { value: 2, text: "Item 2" }
  ]
});

Serializer.addProperty("survey", {
  name: "setChoices",
  type: "boolean",
  default: false,
  onSetValue: function (element, value) {
    if (value) {
      const newChoices = [
        { value: 10, text: "New Value 10" },
        { value: 20, text: "New Value 20" },
        { value: 30, text: "New Value 30" }
      ];      
      element.setPropertyValue("customChoices", newChoices);
    }
  }
});
```
Two issues:
* A list of choices is not updated immediately after changing the value from code;
* The following exception is thrown if you select another element, and then select a survey:
```
react-dom.development.js:12056 Uncaught TypeError: Cannot read properties of undefined (reading 'hasNonDefaultText')
    at ./src/property-grid/matrices.ts.PropertyGridEditorMatrixItemValues.hasMultipleLanguage (survey-creator-core.js:27353:34)
    at ./src/property-grid/matrices.ts.PropertyGridEditorMatrixItemValues.isPropertyEditorSetupEnabled (survey-creator-core.js:27304:19)
    at ./src/property-grid/index.ts.PropertyGridTitleActionsCreator.onGetQuestionTitleActions (survey-creator-core.js:25491:36)
    at Array.eval (survey-creator-core.js:25933:39)
    at ./src/base.ts.Event.fire (survey.core.js:2739:30)
    at ./src/survey.ts.SurveyModel.getUpdatedQuestionTitleActions (survey.core.js:56875:40)
    at ./src/survey.ts.SurveyModel.getUpdatedElementTitleActions (survey.core.js:56868:21)
    at ./src/survey-element.ts.SurveyElement.updateTitleActions (survey.core.js:50538:35)
    at ./src/survey-element.ts.SurveyElement.getTitleActions (survey.core.js:50527:18)
    at QuestionMatrixDynamicModel.get (survey.core.js:50544:25)
    at ./src/react/components/title/title-actions.tsx.TitleActions.render (survey-react-ui.js:3265:27)
    at finishClassComponent (react-dom.development.js:19752:31)
    at updateClassComponent (react-dom.development.js:19698:24)
    at beginWork (react-dom.development.js:21611:16)
    at beginWork$1 (react-dom.development.js:27426:14)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)
    at renderRootSync (react-dom.development.js:26434:7)
    at recoverFromConcurrentError (react-dom.development.js:25850:20)
    at performSyncWorkOnRoot (react-dom.development.js:26096:20)
    at flushSyncCallbacks (react-dom.development.js:12042:22)
    at eval (react-dom.development.js:25651:13)
```

https://github.com/surveyjs/survey-creator/assets/22372972/8afc6667-6f15-4e50-b72b-3c71c4b319eb

**Comment by andrewtelnov** [comment]
@JaneSjs Here is the [updated demo](https://codesandbox.io/s/frosty-snowflake-qx7kv4?file=/src/SurveyCreatorComponent.jsx:592-965).
The property except the real objects. We do some tricks by allowing to set into choices different array types. However, in this case Property Grid editor beleives that it edits an array of live ItemValue objects.
The property definition should be the following:

```js
Serializer.addProperty("survey", {
  name: "setChoices",
  type: "boolean",
  default: false,
  onSetValue: function (element, value) {
    if (value) {
      const newChoices = [
        new ItemValue(10, "New Value 10"),
        new ItemValue(20, "New Value 20"),
        new ItemValue(30, "New Value 30")
      ];
      element.customChoices = newChoices;
    }
  }
});

```

Thank you,
Andrew
