### ISSUE TITLE
Survey Creator for Vue (Nuxt) - The 'Uncaught TypeError: Cannot read properties of null (reading 'json')' exception is thrown when switching to the Themes tab

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#4865]
User Issue: T15412 - Show Theme tab in survey creator
https://surveyjs.answerdesk.io/internal/ticket/details/T15412

A Survey Creator for Vue is integrated within the Nuxt app. The following exception is thrown when switching to the Themes tab.
```
survey-creator-core.js:16113 Uncaught TypeError: Cannot read properties of null (reading 'json')
    at updateBoxShadowSettingsJSON (survey-creator-core.js:16113:1)
    at updateCustomQuestionJSONs (survey-creator-core.js:16489:1)
    at new ThemeBuilder (survey-creator-core.js:14497:1)
    at ./src/components/tabs/theme-plugin.ts.ThemeTabPlugin.activate (survey-creator-core.js:16581:1)
    at ./src/creator-base.ts.CreatorBase.activatePlugin (survey-creator-core.js:20918:1)
    at ./src/creator-base.ts.CreatorBase.switchViewType (survey-creator-core.js:20906:1)
    at ./src/creator-base.ts.CreatorBase.makeNewViewActive (survey-creator-core.js:20890:1)
    at TabbedMenuItem.action (survey-creator-core.js:20611:1)
    at HTMLDivElement.eval (knockout-latest.js:100:1)
```

**Comment by JaneSjs** [comment]
We researched this issue. It appears that the exception occurs because of the following line of code:
```
ComponentCollection.Instance.clear()
;
```
Within the Themes tab, we heavily use custom components to organize property grid editors. Therefore, once the ComponentCollection is cleared, these custom components are removed and the exception occurs.

We will consider updating our code to avoid situations where the clear() function may potentially break the Theme builder functionality.
