### ISSUE TITLE
Cannot read properties of undefined (reading 'length') exception occurs on an attempt to add a new itemvalue for a custom React component

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#4946]
User Issue: T15793 - New React custom widget apply column property
https://surveyjs.answerdesk.io/internal/ticket/details/T15793
***
To reproduce the issue, run this example: [View CodeSandbox](https://codesandbox.io/p/sandbox/pensive-jang-47tmrh?file=%2Fsrc%2FSurveyCreatorComponent.jsx%3A18%2C32). Add the `datagrid` custom question and activate the Columns property grid category. Click + to add a new `itemvalue`. The following exception fails:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at getNextItemText (survey-creator-core.js:39369:22)
    at ./src/property-grid/matrices.ts.PropertyGridEditorMatrix.createNewItem (survey-creator-core.js:33736:93)
    at question.onGetValueForNewRowCallBack (survey-creator-core.js:33604:26)
    at ./src/question_matrixdynamic.ts.QuestionMatrixDynamicModel.getValueForNewRow (survey.core.js:42599:24)
    at QuestionMatrixDynamicModel.set (survey.core.js:42576:60)
    at ./src/question_matrixdynamic.ts.QuestionMatrixDynamicModel.addRowCore (survey.core.js:42848:23)
    at ./src/question_matrixdynamic.ts.QuestionMatrixDynamicModel.addRow (survey.core.js:42808:14)
    at Action.action (survey-creator-core.js:33708:26)
    at onClick (survey-react-ui.js:10280:275)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:25)
    at executeDispatch (react-dom.development.js:9041:3)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:7)
    at processDispatchQueue (react-dom.development.js:9086:5)
    at dispatchEventsForPlugins (react-dom.development.js:9097:3)
    at eval (react-dom.development.js:9288:12)
    at batchedUpdates$1 (react-dom.development.js:26140:12)
    at batchedUpdates (react-dom.development.js:3991:12)
    at dispatchEventForPluginEventSystem (react-dom.development.js:9287:3)
    at dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay (react-dom.development.js:6465:5)
    at dispatchEvent (react-dom.development.js:6457:5)
    at dispatchDiscreteEvent (react-dom.development.js:6430:5)
```

**Comment by andrewtelnov** [comment]
@JaneSjs Properties "columns" and "rows" should be defined. Here is [the updated example](https://codesandbox.io/p/sandbox/busy-wind-x5f9nc?file=%2Fsrc%2FSurveyCreatorComponent.jsx%3A34%2C4).

Thank you,
Andrew

**Comment by hamodey** [comment]
I have copied the example above. I am still getting the issue. Does the fix need an upgrade into the latest SurveyJS?
