### ISSUE TITLE
The Cannot read properties of undefined (reading 'survey') Exception is thrown on an attempt to activate a Themes Tab when a custom theme is assigned to creator.theme

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#4972]
[View CodeSandbox](https://codesandbox.io/p/sandbox/peaceful-dew-hlfwwg?file=%2Fsrc%2Ftheme.js%3A91%2C3)
```
Uncaught TypeError: Cannot read properties of undefined (reading 'survey')
    at ./src/tabs/Designer.tsx.TabDesignerComponent.getStateElements (survey-creator-react.js:3620:40)
    at ./src/react/reactquestion_element.tsx.SurveyElementBase.getRenderedElements (survey-react-ui.js:16500:21)
    at ./src/react/reactquestion_element.tsx.SurveyElementBase.startEndRendering (survey-react-ui.js:16503:29)
    at ./src/react/reactquestion_element.tsx.SurveyElementBase.render (survey-react-ui.js:16474:14)
    at finishClassComponent (react-dom.development.js:19752:31)
    at updateClassComponent (react-dom.development.js:19698:24)
    at beginWork (react-dom.development.js:21611:16)
    at beginWork$1 (react-dom.development.js:27426:14)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)
    at renderRootSync (react-dom.development.js:26434:7)
    at recoverFromConcurrentError (react-dom.development.js:25850:20)
    at performConcurrentWorkOnRoot (react-dom.development.js:25750:22)
    at workLoop (scheduler.development.js:266:34)
    at flushWork (scheduler.development.js:239:14)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:533:21)
```
I specify the theme as follows:
 

![image](https://github.com/surveyjs/survey-creator/assets/22372972/6ba5b4bd-1c2e-42dd-a9f0-01d2ccb7214a)

**Comment by andrewtelnov** [comment]
@JaneSjs The theme doesn't exists "default-exported".
