### ISSUE TITLE
Inputmask - Maximum call stack size exceeded exception is thrown when creating a new logic rule

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#5308]
T17133 - Logic Tab. Inputmask bug
https://surveyjs.answerdesk.io/internal/ticket/details/T17133
***
![image](https://github.com/surveyjs/survey-creator/assets/22372972/e7ce7f3d-0423-4c82-a548-9574733fb86d)

[View Demo](https://codesandbox.io/p/sandbox/nice-hill-zrrl4v?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrz2hmbr0006356ftj9u9qu4%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrz2hmbq0002356fjbjuamqc%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrz2hmbq0003356f8icpp1vc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrz2hmbq0005356fy2fy289b%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrz2hmbq0002356fjbjuamqc%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrz2hmbq0001356fjomrs9ki%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clrz2hmbq0002356fjbjuamqc%2522%252C%2522activeTabId%2522%253A%2522clrz2hmbq0001356fjomrs9ki%2522%257D%252C%2522clrz2hmbq0005356fy2fy289b%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrz2hmbq0004356f3ko0emgt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrz2hmbq0005356fy2fy289b%2522%252C%2522activeTabId%2522%253A%2522clrz2hmbq0004356f3ko0emgt%2522%257D%252C%2522clrz2hmbq0003356f8icpp1vc%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrz2hmbq0003356f8icpp1vc%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

```
Uncaught RangeError: Maximum call stack size exceeded
    at e (inputmask.js:266:43)
    at e (inputmask.js:272:28)
    at e (inputmask.js:272:28)
    at e (inputmask.js:272:28)
    at e (inputmask.js:272:28)
    //...
```

**Comment by JaneSjs** [comment]
> I'm using input mask for this fields:
currency
decimal
email
integer
url
