### ISSUE TITLE
Cannot read properties of undefined (reading 'getRootCss')

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#5486]
**Update**
[The minimum reproduciable example](https://plnkr.co/edit/ZWOGdGPHqow0QXGw).

T18147 - Issue with update to new version of Survey Creator
https://surveyjs.answerdesk.io/internal/ticket/details/T18147
***
A demo is available in the original thread.
```
Uncaught TypeError: Cannot read properties of undefined (reading 'getRootCss')
    at t.render (survey-react-ui.min.js:6:181436)
    at Af (react-dom.production.min.js:133:101)
    at ri (react-dom.production.min.js:132:399)
    at Qk (react-dom.production.min.js:252:71)
    at Ri (react-dom.production.min.js:195:185)
    at Ok (react-dom.production.min.js:195:116)
    at Nd (react-dom.production.min.js:194:492)
    at Qf (react-dom.production.min.js:187:439)
    at Ni (react-dom.production.min.js:185:400)
    at S (react.production.min.js:17:25)
```

**Comment by Andream98** [comment]
Just an FYI, the same happens on the Vue version
```
TypeError: Cannot read properties of undefined (reading 'getRootCss')
    at Proxy.<anonymous> (survey-vue3-ui.es.js:4352:26)
    at renderComponentRoot (runtime-core.esm-bundler.js:887:16)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:6020:46)
    at ReactiveEffect.run (reactivity.esm-bundler.js:177:19)
    at instance.update (runtime-core.esm-bundler.js:6151:16)
    at setupRenderEffect (runtime-core.esm-bundler.js:6161:12)
    at mountComponent (runtime-core.esm-bundler.js:5929:7)
    at processComponent (runtime-core.esm-bundler.js:5883:9)
    at patch (runtime-core.esm-bundler.js:5351:11)
    at mountChildren (runtime-core.esm-bundler.js:5599:7)
```

**Comment by andrewtelnov** [comment]
@Andream98 As a quick fix, change "progressBarType" property value from "buttons" to "pages".
We will solve the issue in the upcoming release.

Thank you,
Andrew

**Comment by Andream98** [comment]
Got it, thank you!
