### ISSUE TITLE
The Cannot convert undefined or null to object exception is thrown when the Themes tab is activated

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#5552]
A problematic demo is available at [T18411 - Re-applying custom theme to editor](https://surveyjs.answerdesk.io/internal/ticket/details/T18411).
```
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Ko (survey-creator-core.min.js:183:534252)
    at survey-creator-core.min.js:183:534308
    at Array.forEach (<anonymous>)
    at Ko (survey-creator-core.min.js:183:534260)
    at Yo (survey-creator-core.min.js:183:534480)
    at t.loadTheme (survey-creator-core.min.js:183:538326)
    at new t (survey-creator-core.min.js:183:536580)
    at e.activate (survey-creator-core.min.js:183:580631)
    at t.activatePlugin (survey-creator-core.min.js:183:604204)
```

**Comment by OlgaLarina** [comment]
BackgroundImage theme attribute is set to "null". It is considered an invalid value. If you wish to reset a background image, set the backgroundImage attribute to an empty string ""

**Comment by marvin-wtt** [comment]
I experienced the same today with `v2.2.1`. The `backgroundImage` attribute was null, even though I never set it to null. So far, I haven't figured out where and why this occurred. I'll post an update if I find the cause or manage to reproduce it.

**Comment by marvin-wtt** [comment]
This happened in my case due to a backend middleware that converts empty strings to null
