### ISSUE TITLE
Action panel disappears after the first interaction with a question

### ISSUE THREAD

**Issue by MartaBento** [surveyjs/survey-creator#5957]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug

### What is the current behavior?
When you add a new question into survey creator, the panel box to change the type, duplicate or delete actions disappears.
On the first interaction, the div `svc-question__content-actions` is completely active and working. After losing focus, if you try to change anything on the question again, the panel doesn't appear.

https://github.com/user-attachments/assets/cab171d7-690f-4dff-8611-ab338b990d0a

Also, in the first interaction, for example, by trying to change the type of question, the error TypeError: this.action is not a function appears.

`Uncaught TypeError: this.action is not a function
    at ./src/entries/core.ts.Action.doAction (survey.core.js:11765:14)
    at onClick (survey-react-ui.js:1245:382)
    at HTMLUnknownElement.callCallback (react-dom.development.js:20565:14)
    at Object.invokeGuardedCallbackImpl (react-dom.development.js:20614:16)
    at invokeGuardedCallback (react-dom.development.js:20689:29)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:20703:25)
    at executeDispatch (react-dom.development.js:32128:3)
    at processDispatchQueueItemsInOrder (react-dom.development.js:32160:7)
    at processDispatchQueue (react-dom.development.js:32173:5)
    at dispatchEventsForPlugins (react-dom.development.js:32184:3)
    at eval (react-dom.development.js:32374:12)
    at batchedUpdates$1 (react-dom.development.js:24953:12)
    at batchedUpdates (react-dom.development.js:28844:12)
    at dispatchEventForPluginEventSystem (react-dom.development.js:32373:3)
    at dispatchEvent (react-dom.development.js:30141:5)
    at dispatchDiscreteEvent (react-dom.development.js:30112:5)`

I was expecting to see:
![image](https://github.com/user-attachments/assets/23a90a81-d18f-46d9-ab02-8d1791bcc0a6)

### What is the expected behavior?

- When I click to change the type of question (e.g., from long text to radio button), I should be able to change it;
- When I click on a question to try to delete it for example, I should see an actions panel, which I currently don't.

### How would you reproduce the current behavior (if this is a bug)?
I could only reproduce this in version `1.12.5`. In version `1.11.10`, which is the stable version we have in production, this is not happening.

**Comment by JaneSjs** [comment]
Hello @MartaBento,
Thank you for reaching out. Wouldy you please clarify whether you can reproduce these both issues on our [online demo](https://surveyjs.io/survey-creator/examples/free-nps-survey-template/)?
